/**
 * Agent Eyes Trimble Connect extension.
 * V3.2 clean source: selection analysis, robust visible-model scan,
 * quantity aggregation, and project-aware ventilation air-type recognition.
 */
export function createTcExtensionHtml(): string {
  return String.raw`<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Agent Eyes</title>
<style>
body{font-family:"Open Sans",system-ui,sans-serif;margin:0;padding:16px;color:#252a2e;font-size:13px}
h1{font-size:15px;margin:0 0 4px}.sub{color:#6a6e79;margin:0 0 16px}
.row{display:flex;justify-content:space-between;gap:10px;padding:6px 0;border-bottom:1px solid #e0e1e9}.row .label{color:#6a6e79}
.ok{color:#006638;font-weight:600}.warn{color:#da212c;font-weight:600}.working{color:#0063a3;font-weight:600}
.box{margin-top:14px;padding:10px;border:1px solid #d9e1e8;border-radius:6px;background:#f7f9fb}.box-title{font-weight:700;margin-bottom:8px;font-size:13px}
.result{white-space:pre-line;font-size:12px;line-height:1.55;word-break:break-word}
.summary-meta{display:flex;justify-content:space-between;gap:8px;margin-bottom:8px;color:#6a6e79;font-size:11px}
.qty-row{padding:8px 0;border-top:1px solid #e0e1e9}.qty-row:first-child{border-top:0}.qty-main{font-weight:700;font-size:12px;line-height:1.45}.qty-sub{color:#555d66;font-size:11px;line-height:1.45;margin-top:2px}.lv-key{color:#6a6e79;font-size:10px;line-height:1.35;margin-top:3px;word-break:break-all}
.actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:16px}button{width:100%;padding:8px 12px;border:0;border-radius:4px;background:#0063a3;color:#fff;font-size:13px;cursor:pointer}button.secondary{background:#4d5963}button.scan{grid-column:1/-1;background:#08783e}button:disabled{background:#b7b9c3;cursor:default}
.note{margin-top:12px;color:#6a6e79;font-size:12px;line-height:1.5}
</style>
</head>
<body>
<h1>Agent Eyes</h1>
<p class="sub">TGA-Auswertung, Modellscan, Luftarten, Mengen und LV-Vorbereitung</p>
<div class="row"><span class="label">Verbindung</span><span id="conn">…</span></div>
<div class="row"><span class="label">Autorisierung</span><span id="auth">…</span></div>
<div class="row"><span class="label">Projekt</span><span id="project">–</span></div>
<div class="row"><span class="label">Auswahl</span><span id="selection">0 Objekte</span></div>
<div class="row"><span class="label">Scan</span><span id="scanStatus">bereit</span></div>
<div class="row"><span class="label">Luftarten</span><span id="airStatus">noch nicht gescannt</span></div>
<div class="row"><span class="label">Letzte Synchronisierung</span><span id="sync">noch nie</span></div>
<div class="box"><div class="box-title">TGA Analyse – aktuelle Auswahl</div><div id="tgaBox" class="result">Noch kein Bauteil ausgewertet.</div></div>
<div class="box"><div class="box-title">V3.2 Mengen / Stückliste</div><div class="summary-meta"><span id="summaryCount">0 Objekte</span><span id="summaryOpen">0 offene Mengen</span></div><div id="qtyBox" class="result">Auswahl analysieren oder sichtbare TGA scannen.</div></div>
<div class="actions"><button id="scanBtn" class="scan" disabled>Sichtbare TGA scannen</button><button id="syncBtn" disabled>Auswahl synchronisieren</button><button id="copyBtn" class="secondary" disabled>Stückliste kopieren</button></div>
<p class="note">Der Scanner liest die aktuell sichtbaren Viewer-Objekte direkt aus Trimble Connect. Falls die Sichtbarkeitsabfrage leer bleibt, wird automatisch „alle geladenen minus versteckte“ verwendet. Luftarten werden zuerst aus IFC-/MEP-Systemdaten erkannt; Objektfarben dienen als zweite, projektspezifische Erkennungsebene.</p>
<script type="module">
import * as WorkspaceAPI from "https://esm.sh/trimble-connect-workspace-api@0.3.34";

const els={conn:document.getElementById("conn"),auth:document.getElementById("auth"),project:document.getElementById("project"),selection:document.getElementById("selection"),scanStatus:document.getElementById("scanStatus"),airStatus:document.getElementById("airStatus"),sync:document.getElementById("sync"),tgaBox:document.getElementById("tgaBox"),qtyBox:document.getElementById("qtyBox"),summaryCount:document.getElementById("summaryCount"),summaryOpen:document.getElementById("summaryOpen"),btn:document.getElementById("syncBtn"),scanBtn:document.getElementById("scanBtn"),copyBtn:document.getElementById("copyBtn")};
const PUSH_URL=new URL("/viewer-state",window.location.href).toString();
const PUSH_INTERVAL_MS=5000,SCAN_PROPERTY_BATCH=50,SCAN_SERVER_CHUNK=300,PROPS_MAX_OBJECTS=30,PROPS_MAX_GROUPS=80,PROPS_MAX_PER_GROUP=200;
let api=null,token=null,project=null,dirty=true,pushing=false,scanning=false,lastSummaryText="";

const AIR_TYPES={zuluft:{label:"Zuluft",code:"ZUL",canonical:"L_Zuluft"},abluft:{label:"Abluft",code:"ABL",canonical:"L_Abluft"},aussenluft:{label:"Außenluft",code:"AUL",canonical:"L_Außenluft"},fortluft:{label:"Fortluft",code:"FOL",canonical:"L_Fortluft"},umluft:{label:"Umluft",code:"UML",canonical:"L_Umluft"},entrauchung:{label:"Entrauchung",code:"ER",canonical:"L_Entrauchung"}};
const learnedAirColors=new Map();

function setText(el,text,cls){if(!el)return;el.textContent=text;el.className=cls||""}
function normalizeToken(value){if(typeof value!=="string")return null;let s=value.trim();if(s.toLowerCase().startsWith("bearer "))s=s.slice(7).trim();return s.split(".").length===3?s:null}
function onEvent(event,data){if(event==="extension.accessToken"){const tok=normalizeToken(data);if(tok){token=tok;setText(els.auth,"erteilt","ok");els.scanBtn.disabled=false;dirty=true}else if(data==="denied")setText(els.auth,"verweigert","warn")}if(event==="viewer.selectionChanged"||event==="viewer.cameraChanged"||event==="viewer.modelLoaded"||event==="viewer.modelStateChanged")dirty=true}
function trimValue(v){if(v===null||v===undefined)return "";const s=typeof v==="object"?JSON.stringify(v):String(v);return s.length>500?s.slice(0,500)+"…":s}
function normalizeAirText(value){return String(value||"").toLowerCase().replace(/ä/g,"ae").replace(/ö/g,"oe").replace(/ü/g,"ue").replace(/ß/g,"ss").replace(/[^a-z0-9]+/g," ").trim()}
function airTypeFromText(value){const s=normalizeAirText(value);const t=new Set(s.split(" ").filter(Boolean));if(s.includes("entrauch")||s.includes("smoke extract")||s.includes("smoke exhaust")||s.includes("rauchabzug")||t.has("rwa"))return "entrauchung";if(s.includes("fortluft")||t.has("fol")||t.has("eha")||s.includes("exhaust air"))return "fortluft";if(s.includes("aussenluft")||t.has("aul")||t.has("oda")||s.includes("outdoor air")||s.includes("fresh air"))return "aussenluft";if(s.includes("zuluft")||t.has("zul")||t.has("sup")||s.includes("supply air"))return "zuluft";if(s.includes("abluft")||t.has("abl")||t.has("eta")||s.includes("extract air"))return "abluft";if(s.includes("umluft")||t.has("uml")||t.has("rca")||s.includes("recirculat")||s.includes("return air"))return "umluft";return null}
function rgbHex(r,g,b){const vals=[r,g,b].map((n)=>{let x=Number(n);if(!Number.isFinite(x))x=0;if(x>=0&&x<=1)x*=255;x=Math.max(0,Math.min(255,Math.round(x)));return x.toString(16).padStart(2,"0")});return "#"+vals.join("").toUpperCase()}
function normalizeColor(value){if(value===null||value===undefined)return null;if(typeof value==="string"){const h=value.trim().match(/#?([0-9a-f]{6})(?:[0-9a-f]{2})?/i);if(h)return "#"+h[1].toUpperCase();const r=value.match(/rgba?\s*\(\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?)/i);if(r)return rgbHex(r[1],r[2],r[3])}if(Array.isArray(value)&&value.length>=3)return rgbHex(value[0],value[1],value[2]);if(typeof value==="object"){const r=value.r??value.red??value.R,g=value.g??value.green??value.G,b=value.b??value.blue??value.B;if(r!=null&&g!=null&&b!=null)return rgbHex(r,g,b)}return null}
function hexRgb(hex){if(!hex||!/^#[0-9A-F]{6}$/i.test(hex))return null;return [parseInt(hex.slice(1,3),16),parseInt(hex.slice(3,5),16),parseInt(hex.slice(5,7),16)]}
function standardAirFromColor(color){const rgb=hexRgb(color);if(!rgb)return null;const r=rgb[0],g=rgb[1],b=rgb[2],max=Math.max(r,g,b),min=Math.min(r,g,b);if(max<70||max-min<35)return null;if(g>r*1.18&&g>b*1.10)return "aussenluft";if(b>r*1.18&&b>g*1.10)return "zuluft";if(r>175&&g>145&&b<125)return "abluft";if(r>165&&g>75&&g<175&&b<105)return "umluft";if(r>80&&r<185&&g>35&&g<135&&b<95)return "fortluft";return null}
function objectAirText(obj){const values=[obj.class,obj.name,obj.objectType,obj.description];for(const value of Object.values(obj.product||{}))values.push(value);for(const group of obj.propertySets||[])for(const prop of group.props||[])values.push(prop.name,prop.value);return values.filter(Boolean).join(" ")}
function appendDerived(obj,name,value){obj.propertySets=obj.propertySets||[];let group=obj.propertySets.find((g)=>g.name==="Agent Eyes Derived");if(!group){group={name:"Agent Eyes Derived",props:[]};obj.propertySets.push(group)}if(!group.props.some((p)=>p.name===name))group.props.push({name,value})}
function learnAirColor(obj){const type=airTypeFromText(objectAirText(obj)),color=normalizeColor(obj.color);if(!type||!color)return;if(!learnedAirColors.has(color))learnedAirColors.set(color,new Map());const m=learnedAirColors.get(color);m.set(type,(m.get(type)||0)+1)}
function learnedAirFromColor(color){const m=learnedAirColors.get(color);if(!m)return null;let best=null,count=0;for(const [type,n] of m){if(n>count){best=type;count=n}}return best}
function enrichAirMetadata(obj){const explicit=airTypeFromText(objectAirText(obj)),color=normalizeColor(obj.color),learned=learnedAirFromColor(color),inferred=explicit||learned||standardAirFromColor(color);if(!inferred)return obj;appendDerived(obj,"Agent Eyes Air Type",AIR_TYPES[inferred].label);appendDerived(obj,"Agent Eyes Air Source",explicit?"IFC/MEP-Systemdaten":(learned?"Projektfarbe":"Normfarb-Fallback"));if(!explicit)appendDerived(obj,"Tech-Medium",AIR_TYPES[inferred].canonical);if(color)appendDerived(obj,"Agent Eyes Color",color);return obj}

function addDerivedProperties(result){const text=[result.name,result.objectType,result.description,...Object.values(result.product||{})].filter(Boolean).join(" ");const derived=[];const roundBsk=text.match(/FKRS[- ]?EU(?:\/DE)?\/(\d{2,4})(?:\/|$)/i);if(roundBsk)derived.push({name:"DN",value:String(Number(roundBsk[1]))});const rect=text.match(/FK2[- ]?EU(?:\/DE)?\/(\d{2,4})\s*x\s*(\d{2,4})\s*x\s*(\d{2,4})(?:\/|$)/i);if(rect){derived.push({name:"Geom-Side 1 (mm)",value:String(Number(rect[1]))},{name:"Geom-Side 2 (mm)",value:String(Number(rect[2]))},{name:"Geom-Length (mm)",value:String(Number(rect[3]))})}if(derived.length){result.propertySets=result.propertySets||[];let group=result.propertySets.find((g)=>g.name==="Agent Eyes Derived");if(!group){group={name:"Agent Eyes Derived",props:[]};result.propertySets.push(group)}group.props.push(...derived)}return result}
function scanPropertyWanted(name){return /(geom|side|width|height|breite|höhe|hoehe|diam|durchmesser|length|länge|laenge|size|dimension|medium|system|layer|storey|geschoss|floor|level|insulation|dämm|daemm|manufacturer|hersteller|fabrikat|flow|volumen|pressure|druck|zeta|tag|kennzeichen|color|colour|farbe|rgb|appearance|presentation)/i.test(String(name||""))}
function trimObject(obj,scanMode){const product=obj?.product||{};const productData={};for(const [key,value] of Object.entries(product)){if(value===null||value===undefined||typeof value==="string"||typeof value==="number"||typeof value==="boolean")productData[key]=trimValue(value)}const propertySets=[];for(const group of (obj?.properties||[]).slice(0,PROPS_MAX_GROUPS)){let props=(group.properties||[]);if(scanMode)props=props.filter((p)=>scanPropertyWanted(p.name)).slice(0,50);else props=props.slice(0,PROPS_MAX_PER_GROUP);if(props.length)propertySets.push({name:group.name,props:props.map((p)=>({name:p.name,value:trimValue(p.value)}))})}return enrichAirMetadata(addDerivedProperties({runtimeId:obj?.id,class:obj?.class,name:product.name,objectType:product.objectType,description:product.description,color:obj?.color,product:productData,propertySets}))}

async function loadedModels(){try{return (await api.viewer.getModels("loaded"))||[]}catch{return []}}
function normalizeViewerGroups(groups){return (groups||[]).map((group)=>{const objects=Array.isArray(group?.objects)?group.objects:[];const ids=objects.length?objects.map((o)=>o?.id).filter((id)=>id!==undefined&&id!==null):Array.from(group?.objectRuntimeIds||[]);return {modelId:group?.modelId,objects,objectRuntimeIds:Array.from(new Set(ids))}}).filter((g)=>g.modelId&&g.objectRuntimeIds.length)}
function groupCount(groups){return (groups||[]).reduce((sum,g)=>sum+(g.objectRuntimeIds||[]).length,0)}
function subtractHidden(allGroups,hiddenGroups){const hidden=new Map();for(const g of hiddenGroups)hidden.set(g.modelId,new Set(g.objectRuntimeIds));return allGroups.map((g)=>{const block=hidden.get(g.modelId)||new Set();return {modelId:g.modelId,objects:(g.objects||[]).filter((o)=>!block.has(o.id)),objectRuntimeIds:g.objectRuntimeIds.filter((id)=>!block.has(id))}}).filter((g)=>g.objectRuntimeIds.length)}
async function getVisibleGroupsSafe(){try{const direct=normalizeViewerGroups(await api.viewer.getObjects(undefined,{visible:true}));if(groupCount(direct)>0)return {groups:direct,mode:"visible:true",allCount:groupCount(direct),hiddenCount:0}}catch(err){console.warn("visible:true query failed",err)}let all=[],hidden=[];try{all=normalizeViewerGroups(await api.viewer.getObjects())}catch(err){console.warn("all-object query failed",err)}if(groupCount(all)===0)return {groups:[],mode:"none",allCount:0,hiddenCount:0};try{hidden=normalizeViewerGroups(await api.viewer.getObjects(undefined,{visible:false}))}catch(err){console.warn("hidden-object query failed",err)}return {groups:subtractHidden(all,hidden),mode:"all-minus-hidden",allCount:groupCount(all),hiddenCount:groupCount(hidden)}}

async function capture(includeSnapshot){const state={capturedAt:Date.now()};try{state.camera=await api.viewer.getCamera()}catch{}const models=await loadedModels();state.models=models.map((m)=>({id:m.id,versionId:m.versionId,name:m.name}));try{const selection=await api.viewer.getSelection();const entries=[];let count=0,propsBudget=PROPS_MAX_OBJECTS;for(const sel of selection||[]){const runtimeIds=(sel.objectRuntimeIds||[]).slice(0,500);count+=runtimeIds.length;const entry={modelId:sel.modelId,objectRuntimeIds:runtimeIds};try{entry.externalIds=await api.viewer.convertToObjectIds(sel.modelId,runtimeIds)}catch{}if(propsBudget>0&&runtimeIds.length){const propIds=runtimeIds.slice(0,propsBudget);try{const raw=await api.viewer.getObjectProperties(sel.modelId,propIds);entry.properties=(raw||[]).map((obj,i)=>{const trimmed=trimObject(obj,false);if(entry.externalIds&&entry.externalIds[i])trimmed.externalId=entry.externalIds[i];return trimmed});propsBudget-=propIds.length}catch(err){console.warn("getObjectProperties failed",err)}}const model=models.find((m)=>m.id===sel.modelId);if(model)entry.modelName=model.name;entries.push(entry)}state.selection=entries;setText(els.selection,count+" Objekt"+(count===1?"":"e"))}catch(err){console.warn("Selection capture failed",err)}if(includeSnapshot!==false){try{state.snapshot=await api.viewer.getSnapshot()}catch{}}if(project)state.project={id:project.id,name:project.name,location:project.location};return state}
async function postAnalysisPayload(payload){const res=await fetch(PUSH_URL,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify(payload)});if(!res.ok){let detail="";try{detail=(await res.json()).error||""}catch{}throw new Error("HTTP "+res.status+(detail?" - "+detail:""))}return await res.json()}
function formatNumber(value,decimals){const n=Number(value);if(!Number.isFinite(n))return "-";return n.toLocaleString("de-DE",{minimumFractionDigits:decimals,maximumFractionDigits:decimals})}
function dimensionText(c){if(c.shape==="rectangular")return (c.widthMm!=null?formatNumber(c.widthMm,0):"?")+" × "+(c.heightMm!=null?formatNumber(c.heightMm,0):"?")+" mm";if(c.shape==="round")return "Ø "+(c.diameterMm!=null?formatNumber(c.diameterMm,0):"?")+" mm";return "-"}
function productSourceText(c){const e=c.productEnrichment;if(!e||!Array.isArray(e.sources)||!e.sources.length)return "-";return e.sources.slice(0,2).map((s)=>s.source+": "+(s.title||s.productSeries||s.manufacturer||"Produktquelle")).join(" | ")}
function etimText(c){if(!Array.isArray(c.etimMatches)||!c.etimMatches.length)return "-";const f=c.etimMatches[0];return (f.referenceCode?f.referenceCode+" – ":"")+(f.name||"ETIM")}
function normalizeKeyPart(value){return String(value||"-").trim().toLowerCase().replace(/ä/g,"ae").replace(/ö/g,"oe").replace(/ü/g,"ue").replace(/ß/g,"ss").replace(/[^a-z0-9.]+/g,"_").replace(/^_+|_+$/g,"")}
function buildLvKey(c){const dim=c.shape==="round"?"dn_"+String(c.diameterMm!=null?Math.round(Number(c.diameterMm)):"x"):c.shape==="rectangular"?"b_"+String(c.widthMm!=null?Math.round(Number(c.widthMm)):"x")+"_h_"+String(c.heightMm!=null?Math.round(Number(c.heightMm)):"x"):"dim_x";return [normalizeKeyPart(c.type||c.label),dim,normalizeKeyPart(c.productType||c.objectType),c.insulationMm!=null?"daemm_"+Math.round(Number(c.insulationMm)):"daemm_x"].join("|")}
function renderTgaAnalysis(list){if(!list||!list.length){els.tgaBox.textContent="Kein Bauteil ausgewählt.";return}const c=list[0];let quantity="-";if(c.quantity!=null)quantity=formatNumber(c.quantity,c.quantityUnit==="St."?0:2)+" "+(c.quantityUnit||"");else if(c.quantityUnit)quantity=c.quantityUnit+" – Menge offen";const manufacturer=c.manufacturer||c.productEnrichment?.manufacturer||"-",productType=c.productType||c.productEnrichment?.productSeries||c.objectType||"-";const lines=["Typ: "+(c.label||"-"),"IFC: "+(c.ifcType||"-"),"Produkt: "+(c.name||"-"),"Produkt-Typ: "+productType,"Fabrikat: "+manufacturer,"Beschreibung: "+(c.description||"-"),"Layer: "+(c.layer||"-"),"Dimension: "+dimensionText(c),"System: "+(c.system||"-"),"Geschoss: "+(c.storey||"-"),"Länge: "+(c.lengthMm!=null?formatNumber(c.lengthMm/1000,2)+" m":"-"),"Dämmung: "+(c.insulationMm!=null?formatNumber(c.insulationMm,0)+" mm":"-"),"Volumenstrom: "+(c.airflowM3h!=null?formatNumber(c.airflowM3h,0)+" m³/h":"-"),"Geschwindigkeit: "+(c.velocityMs!=null?formatNumber(c.velocityMs,2)+" m/s":"-"),"Druckverlust: "+(c.pressureLossPa!=null?formatNumber(c.pressureLossPa,1)+" Pa":"-"),"ζ: "+(c.zeta!=null?formatNumber(c.zeta,2):"-"),"Menge: "+quantity,"VDI 3805: "+(c.vdi3805Scope||"-"),"ETIM: "+etimText(c),"Produktquelle: "+productSourceText(c),"LV-Key: "+buildLvKey(c)];if(c.guid)lines.push("IFC GUID: "+c.guid);if(c.quantityNote)lines.push("Hinweis: "+c.quantityNote);if(c.matchedBy?.length)lines.push("Erkennung: "+c.matchedBy.join(", "));if(list.length>1)lines.push("","Ausgewählte Bauteile: "+list.length);els.tgaBox.textContent=lines.join("\n")}
function compactAnalysis(c){return {domain:c.domain,type:c.type,label:c.label,ifcType:c.ifcType,name:c.name,description:c.description,objectType:c.objectType,manufacturer:c.manufacturer,productType:c.productType,system:c.system,storey:c.storey,shape:c.shape,widthMm:c.widthMm,heightMm:c.heightMm,diameterMm:c.diameterMm,lengthMm:c.lengthMm,insulationMm:c.insulationMm,quantityUnit:c.quantityUnit,quantity:c.quantity,productEnrichment:c.productEnrichment}}
function aggregateTga(list){const groups=new Map();for(const c of list||[]){const dim=dimensionText(c),manufacturer=c.manufacturer||c.productEnrichment?.manufacturer||"-",productType=c.productType||c.productEnrichment?.productSeries||c.objectType||"-",unit=c.quantityUnit||"",insulation=c.insulationMm!=null?Number(c.insulationMm):null,key=[c.type||c.label||"unknown",dim,manufacturer,productType,unit,insulation==null?"":String(insulation)].join("||");if(!groups.has(key))groups.set(key,{label:c.label||"Nicht erkannt",dimension:dim,manufacturer,productType,insulationMm:insulation,unit,quantity:0,knownQuantityCount:0,count:0,systems:new Set(),storeys:new Set(),lvKey:buildLvKey(c)});const row=groups.get(key);row.count++;if(c.quantity!=null&&Number.isFinite(Number(c.quantity))){row.quantity+=Number(c.quantity);row.knownQuantityCount++}if(c.system)row.systems.add(c.system);if(c.storey)row.storeys.add(c.storey)}return Array.from(groups.values()).sort((a,b)=>String(a.label).localeCompare(String(b.label),"de")||String(a.dimension).localeCompare(String(b.dimension),"de",{numeric:true}))}
function compactSet(setValue){const values=Array.from(setValue||[]);if(!values.length)return "-";if(values.length<=2)return values.join(", ");return values.slice(0,2).join(", ")+" +"+String(values.length-2)}
function renderAirStatus(list){const counts={zuluft:0,abluft:0,aussenluft:0,fortluft:0,umluft:0,entrauchung:0};for(const c of list||[]){const type=airTypeFromText(c.system);if(type&&counts[type]!==undefined)counts[type]++}const parts=[];for(const key of ["zuluft","abluft","aussenluft","fortluft","umluft","entrauchung"])if(counts[key]>0)parts.push(AIR_TYPES[key].code+" "+counts[key]);setText(els.airStatus,parts.length?parts.join(" · "):"keine Luftart erkannt",parts.length?"ok":"warn")}
function renderQuantitySummary(list,meta){const source=meta?.source||"Auswahl",visibleTotal=meta?.visibleTotal;if(!list||!list.length){els.summaryCount.textContent=source+": 0 TGA-Objekte";els.summaryOpen.textContent="0 offene Mengen";els.qtyBox.textContent=source==="Modellscan"?"Keine TGA-Bauteile in den sichtbaren Objekten erkannt.":"Keine Bauteile ausgewählt.";els.copyBtn.disabled=true;lastSummaryText="";if(source==="Modellscan")renderAirStatus([]);return}const rows=aggregateTga(list),openRows=rows.filter((r)=>r.knownQuantityCount<r.count);els.summaryCount.textContent=source+": "+list.length+" TGA-Objekte / "+rows.length+" Gruppen"+(visibleTotal!=null?" / "+visibleTotal+" sichtbar":"");els.summaryOpen.textContent=openRows.length+" offene Mengen";els.qtyBox.textContent="";const textLines=["Agent Eyes V3.2 Stückliste – "+source,"TGA-Objekte: "+list.length,visibleTotal!=null?"Sichtbare Objekte geprüft: "+visibleTotal:"","Gruppen: "+rows.length,""];rows.forEach((row,index)=>{let quantityText="Menge offen";if(row.knownQuantityCount>0){quantityText=formatNumber(row.quantity,row.unit==="St."?0:2)+(row.unit?" "+row.unit:"");if(row.knownQuantityCount<row.count)quantityText+=" + offen"}else if(row.unit)quantityText=row.unit+" – Menge offen";const div=document.createElement("div");div.className="qty-row";const main=document.createElement("div");main.className="qty-main";main.textContent=String(index+1)+". "+row.label+" | "+row.dimension+" | "+quantityText;const sub=document.createElement("div");sub.className="qty-sub";sub.textContent="Objekte: "+row.count+" | Fabrikat: "+row.manufacturer+" | Typ: "+row.productType+" | System: "+compactSet(row.systems)+" | Geschoss: "+compactSet(row.storeys)+(row.insulationMm!=null?" | Dämmung: "+formatNumber(row.insulationMm,0)+" mm":"");const lv=document.createElement("div");lv.className="lv-key";lv.textContent="LV-Key: "+row.lvKey;div.append(main,sub,lv);els.qtyBox.appendChild(div);textLines.push(String(index+1)+". "+row.label+" | "+row.dimension+" | "+quantityText,"   Objekte: "+row.count+" | Fabrikat: "+row.manufacturer+" | Typ: "+row.productType+" | System: "+compactSet(row.systems)+" | Geschoss: "+compactSet(row.storeys),"   LV-Key: "+row.lvKey,"")});lastSummaryText=textLines.join("\n");els.copyBtn.disabled=false;if(source==="Modellscan")renderAirStatus(list)}
async function copySummary(){if(!lastSummaryText)return;try{await navigator.clipboard.writeText(lastSummaryText);els.copyBtn.textContent="Kopiert ✓"}catch{els.copyBtn.textContent="Kopieren fehlgeschlagen"}setTimeout(()=>{els.copyBtn.textContent="Stückliste kopieren"},1500)}
async function push(force){if(!api||!token||pushing||scanning)return;if(!dirty&&!force)return;pushing=true;try{const state=await capture(true),data=await postAnalysisPayload(state),analysis=data.tgaAnalysis||[];renderTgaAnalysis(analysis);renderQuantitySummary(analysis,{source:"Auswahl"});dirty=false;setText(els.sync,new Date().toLocaleTimeString("de-DE"),"ok")}catch(err){setText(els.sync,"Fehler","warn");els.tgaBox.textContent="TGA-Auswertung fehlgeschlagen:\n"+String(err)}finally{pushing=false}}
async function analyzeScanEntries(entries,models){if(!entries.length)return[];const payload={capturedAt:Date.now(),project:project?{id:project.id,name:project.name,location:project.location}:undefined,models:models.map((m)=>({id:m.id,versionId:m.versionId,name:m.name})),selection:entries};const data=await postAnalysisPayload(payload);return data.tgaAnalysis||[]}
async function restoreViewerStateAfterScan(){try{const state=await capture(false);await postAnalysisPayload(state);dirty=false}catch(err){console.warn("Viewer state restore after scan failed",err);dirty=true}}

async function scanVisibleTga(){if(!api||!token||scanning)return;scanning=true;pushing=false;els.scanBtn.disabled=true;els.btn.disabled=true;els.copyBtn.disabled=true;setText(els.scanStatus,"sichtbare Objekte werden gelesen…","working");const found=[];let visibleTotal=0,processed=0,propertyErrors=0,pendingEntries=[],pendingCount=0;try{const models=await loadedModels(),modelMap=new Map(models.map((m)=>[m.id,m])),visibility=await getVisibleGroupsSafe(),groups=visibility.groups;visibleTotal=groupCount(groups);if(visibleTotal===0){renderQuantitySummary([],{source:"Modellscan",visibleTotal:0});setText(els.scanStatus,"keine sichtbaren Objekte | "+visibility.mode,"warn");return}setText(els.scanStatus,"0 / "+visibleTotal+" Objekte | "+visibility.mode,"working");const flush=async()=>{if(!pendingEntries.length)return;const analyzed=await analyzeScanEntries(pendingEntries,models);for(const c of analyzed)if(c&&c.type&&c.type!=="unknown")found.push(compactAnalysis(c));pendingEntries=[];pendingCount=0;renderQuantitySummary(found,{source:"Modellscan",visibleTotal})};for(const group of groups){const model=modelMap.get(group.modelId),ids=group.objectRuntimeIds,byId=new Map((group.objects||[]).map((obj)=>[obj.id,obj]));for(let offset=0;offset<ids.length;offset+=SCAN_PROPERTY_BATCH){const batchIds=ids.slice(offset,offset+SCAN_PROPERTY_BATCH);let rawProps=batchIds.map((id)=>byId.get(id)).filter(Boolean);const have=new Set(rawProps.map((o)=>o.id)),missing=batchIds.filter((id)=>!have.has(id));if(missing.length){try{const fetched=(await api.viewer.getObjectProperties(group.modelId,missing))||[];rawProps=rawProps.concat(fetched)}catch(err){propertyErrors+=missing.length;console.warn("scan getObjectProperties failed",group.modelId,err)}}const properties=rawProps.map((obj)=>trimObject(obj,true));for(const p of properties)learnAirColor(p);for(const p of properties)enrichAirMetadata(p);if(properties.length){pendingEntries.push({modelId:group.modelId,modelName:model?.name,objectRuntimeIds:batchIds,properties});pendingCount+=properties.length}processed+=batchIds.length;setText(els.scanStatus,processed+" / "+visibleTotal+" Objekte | "+visibility.mode,"working");if(pendingCount>=SCAN_SERVER_CHUNK)await flush()}}await flush();renderQuantitySummary(found,{source:"Modellscan",visibleTotal});setText(els.scanStatus,found.length+" TGA aus "+visibleTotal+" sichtbar | "+visibility.mode+(propertyErrors?" | "+propertyErrors+" Lesefehler":""),propertyErrors?"warn":"ok");await restoreViewerStateAfterScan()}catch(err){setText(els.scanStatus,"Scan-Fehler","warn");els.qtyBox.textContent="Modellscan fehlgeschlagen:\n"+String(err);console.error("visible TGA scan failed",err);await restoreViewerStateAfterScan()}finally{scanning=false;els.scanBtn.disabled=!token;els.btn.disabled=false}}

async function init(){try{api=await WorkspaceAPI.connect(window.parent,onEvent,30000);setText(els.conn,"verbunden","ok")}catch{setText(els.conn,"Fehler","warn");return}try{project=await api.project.getCurrentProject();setText(els.project,project?.name||project?.id||"–")}catch{}try{const result=await api.extension.requestPermission("accesstoken"),tok=normalizeToken(result);if(tok){token=tok;setText(els.auth,"erteilt","ok");els.scanBtn.disabled=false}else if(result==="denied")setText(els.auth,"verweigert","warn");else setText(els.auth,"warte…")}catch{setText(els.auth,"Fehler","warn")}els.btn.disabled=false;els.btn.addEventListener("click",()=>push(true));els.scanBtn.addEventListener("click",scanVisibleTga);els.copyBtn.addEventListener("click",copySummary);setInterval(()=>push(false),PUSH_INTERVAL_MS);setInterval(()=>{dirty=true},30000)}
init();
</script>
</body>
</html>`;
}
